fix: add more tests codelists and check actions
Effectively, our workflow is our test runner here.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -21,3 +21,55 @@ jobs:
         uses: ./
         with:
             directory: gh-research-testing
+
+  test-codelists:
+    runs-on: ubuntu-20.04
+    name: Test codelists failure
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Test project with failing codelists check
+        uses: ./
+        id: codelists
+        continue-on-error: true
+        with:
+            directory: tests/codelists
+      - name: Assert codelists check failed
+        run: |
+            if test "${{ steps.codelists.outcome }}" != "failure"; then
+                echo "Action should have failed with codelists error"
+                exit 1
+            fi
+
+  test-check:
+    runs-on: ubuntu-20.04
+    name: Test dataset check failure
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Test project with failing codelists check
+        uses: ./
+        id: dataset
+        continue-on-error: true
+        with:
+            directory: tests/dataset
+            users: '@nobody' 
+        env:
+            GITHUB_REPOSITORY: ${{ github.repo }}
+      - name: Assert check failed and created issue
+        env:
+            ISSUE_URL: ${{ steps.dataset.outputs.issue }}
+        run: |
+            fail() { 
+                echo "$@"
+                exit 1
+            }
+            cleanup() { 
+                gh issue close $ISSUE_URL || true
+            }
+            trap cleanup EXIT
+            test "${{ steps.dataset.outcome }}" = "failure" || fail "Action should have failed with dataset error"
+            test -n "$ISSUE_URL" || fail "No issue url output from dataset step"
+            gh issue view $ISSUE_URL || fail "Could not view issue at $ISSUE_URL"
+
+
